#!/bin/bash

FILE=notes.txt
nvim_bin=$(which nvim)

if test -f "$FILE"; then

	if [ -s "$FILE" ]; then
		$nvim_bin $FILE

	else
		echo "------------------
NOTES
------------------" > $FILE
		$nvim_bin $FILE
	fi

else
	touch "$FILE"
		echo "------------------
NOTES
------------------" > $FILE
		$nvim_bin $FILE
fi
